"""baremes

La table des quatre baremes de la section 6. **DDL uniquement** : les quatre
lignes ne sont PAS posees ici.

Ce n'est pas un oubli. Une migration qui insere des donnees ne sait pas quoi
faire quand la ligne existe deja, et elle ne rattrape pas une installation
creee avant elle — or le lot 2a est deja sur `main` et peut avoir ete installe.
Les quatre lignes sont donc creees **a la volee**, par `assurer_baremes()`, au
premier acces. C'est idempotent, et une ligne manquante ne peut jamais casser
un ecran.

`type` est la cle primaire : quatre types fixes, adresses par
`/api/baremes/{type}`, et un JSON qui ne porte aucun `id`.

Revision ID: 38af14d3d6c7
Revises: 49e79c0d2b7a
Create Date: 2026-09-16 14:55:16.712654
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38af14d3d6c7'
down_revision: Union[str, None] = '49e79c0d2b7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bareme',
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('libelle', sa.String(length=80), nullable=False),
    sa.Column('machines_ids', sa.Text(), nullable=False),
    sa.Column('donnees', sa.Text(), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('type')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bareme')
    # ### end Alembic commands ###
