"""referentiels: machines, cylindres, matieres, outils, clients, options

Les six tables de la section 5 du contrat. **DDL uniquement** : aucune donnee
n'est posee ici. Un referentiel part VIDE chez le client, comme les tarifs —
livrer le parc de presses d'un autre atelier n'aurait aucun sens.

Les types maison se rendent en `sa.String` et `sa.Text` (cf. `rendre_item` dans
`alembic/env.py`) : une migration deja appliquee chez un client ne doit pas
dependre d'un module de l'application qu'on est libre de renommer demain.

Revision ID: 49e79c0d2b7a
Revises: 745249fbea7d
Create Date: 2026-09-16 14:42:28.500003
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49e79c0d2b7a'
down_revision: Union[str, None] = '745249fbea7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=160), nullable=False),
    sa.Column('contact', sa.String(length=160), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telephone', sa.String(length=32), nullable=True),
    sa.Column('intervalle_dev_min_mm', sa.String(length=16), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_table('machine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=120), nullable=False),
    sa.Column('laize_utile_mm', sa.String(length=16), nullable=False),
    sa.Column('laize_maxi_mm', sa.String(length=16), nullable=False),
    sa.Column('vitesse_moyenne_m_h', sa.Integer(), nullable=False),
    sa.Column('duree_calage_h', sa.String(length=16), nullable=False),
    sa.Column('nb_groupes_couleurs', sa.Integer(), nullable=False),
    sa.Column('modules', sa.Text(), nullable=False),
    sa.Column('diametre_bobine_maxi_mm', sa.String(length=16), nullable=False),
    sa.Column('temps_changement_bobine_h', sa.String(length=16), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_table('matiere',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=120), nullable=False),
    sa.Column('grammage_g_m2', sa.String(length=16), nullable=False),
    sa.Column('prix_m2_eur', sa.String(length=16), nullable=False),
    sa.Column('epaisseur_reelle_micron', sa.Integer(), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_table('option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('libelle', sa.String(length=160), nullable=False),
    sa.Column('groupes_couleurs_requis', sa.Integer(), nullable=False),
    sa.Column('modules_requis', sa.Text(), nullable=False),
    sa.Column('coefficient_vitesse', sa.String(length=16), nullable=False),
    sa.Column('coefficient_gache', sa.String(length=16), nullable=False),
    sa.Column('temps_calage_ajoute_h', sa.String(length=16), nullable=False),
    sa.Column('tarification', sa.Text(), nullable=False),
    sa.Column('silhouette_automatique', sa.Boolean(), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('cylindre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('developpe_mm', sa.String(length=16), nullable=False),
    sa.Column('nb_dents', sa.Integer(), nullable=True),
    sa.Column('repere_machine', sa.String(length=32), nullable=False),
    sa.Column('nb_porte_cliches', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('date_inventaire', sa.Date(), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machine.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('machine_id', 'repere_machine', name='uq_cylindre_machine_repere')
    )
    with op.batch_alter_table('cylindre', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cylindre_machine_id'), ['machine_id'], unique=False)

    op.create_table('outil',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=64), nullable=False),
    sa.Column('largeur_mm', sa.String(length=16), nullable=False),
    sa.Column('hauteur_mm', sa.String(length=16), nullable=False),
    sa.Column('nb_poses_laize', sa.Integer(), nullable=False),
    sa.Column('nb_poses_developpe', sa.Integer(), nullable=False),
    sa.Column('forme_speciale', sa.Boolean(), nullable=False),
    sa.Column('cylindre_id', sa.Integer(), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cylindre_id'], ['cylindre.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    with op.batch_alter_table('outil', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outil_cylindre_id'), ['cylindre_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outil', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outil_cylindre_id'))

    op.drop_table('outil')
    with op.batch_alter_table('cylindre', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cylindre_machine_id'))

    op.drop_table('cylindre')
    op.drop_table('option')
    op.drop_table('matiere')
    op.drop_table('machine')
    op.drop_table('client')
    # ### end Alembic commands ###
