"""noyau: comptes, sessions, parametres de couts

Revision ID: 745249fbea7d
Revises:
Create Date: 2026-08-20 17:09:21.906091
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '745249fbea7d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parametres_couts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marge_standard_pct', sa.String(length=16), nullable=False),
    sa.Column('cout_exploitation_machine_eur_h', sa.String(length=16), nullable=True),
    sa.Column('cout_operateur_eur_h', sa.String(length=16), nullable=True),
    sa.Column('marge_confort_roulage_mm', sa.Integer(), nullable=True),
    sa.Column('cliche_prix_couleur_eur', sa.String(length=16), nullable=True),
    sa.Column('outil_base_eur', sa.String(length=16), nullable=True),
    sa.Column('outil_par_trace_eur', sa.String(length=16), nullable=True),
    sa.Column('surcout_forme_speciale_facteur', sa.String(length=16), nullable=True),
    sa.Column('calage_forfait_eur', sa.String(length=16), nullable=True),
    sa.Column('finitions_prix_m2_eur', sa.String(length=16), nullable=True),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('utilisateur',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifiant', sa.String(length=64), nullable=False),
    sa.Column('mot_de_passe_hache', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifiant')
    )
    op.create_table('session_utilisateur',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jeton_hache', sa.String(length=64), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expire_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoquee_le', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('session_utilisateur', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_utilisateur_jeton_hache'), ['jeton_hache'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_utilisateur', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_utilisateur_jeton_hache'))

    op.drop_table('session_utilisateur')
    op.drop_table('utilisateur')
    op.drop_table('parametres_couts')
    # ### end Alembic commands ###
